# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
title: D'Last Code Bender
email: dlastcodebender@gmail.com
description: >-
  Welcome to D'Last Code Bender! A site showcasing coding tutorials, tips, and tricks. 
  Explore the world of code and creativity with us.
baseurl: "" # Leave empty for root domain (https://dlastcodebender.com.ng)
url: "https://dlastcodebender.com.ng" # Full URL of your site
twitter_username: dlastcodebender
github_username: dlastcodebender

# Permalink structure for clean URLs (no .html)
permalink: /:title/

# Theme settings
theme: minima # Default theme
plugins:
  - jekyll-feed # Generates RSS feeds

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - _site/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock

# Include additional files to process
include:
  - assets/ # Ensures assets like CSS/JS/JSON are included
  - posts.json

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # GitHub-flavored Markdown for compatibility

# Collections
collections:
  posts:
    output: true # Generates a /:title/ permalink for each post

# Build settings
future: true # Publish posts with future dates
relative_permalinks: false # Ensures absolute URLs work properly




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
